# Generated by Django 6.0.1 on 2026-03-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_post_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
    ]
